# TOML file for fpm as described at https://github.com/fortran-lang/fpm/blob/master/manifest-reference.md
name = "what"
version = "1.0.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2021 John S. Urban"
description = "find SCC metadata strings in files"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false

[dependencies]

[dependencies.M_CLI2]
   git = "https://github.com/urbanjost/M_CLI2.git"
[dependencies.M_strings]
   git = "https://github.com/urbanjost/M_strings.git"
[dependencies.M_msg]
   git = "https://github.com/urbanjost/M_msg.git"

[[executable]]
name = "what"
source-dir = "app/"
main="what.f90"
